export const dict = {
  tr: {
    nav: { home: "Genel Bakış", ko: "Knight Online", cs2: "CS2", scan: "Fırsat Tarayıcı", alerts: "Uyarılar", pricing: "Planlar", about: "Yöntem" },
    hero: { title: "Oyun pazarının fiyat radarı", sub: "Knight Online GB ve CS2 skin fiyatlarını 7 pazar yerinden saatlik topluyor, trendi ve nakde çevirince eline geçeni gösteriyoruz.", cta: "Fırsatları gör", updated: "Güncelleme", sources: "kaynak canlı" },
    kpi: { fx: "Kur", bestServer: "En değerli GB", cheapest: "En ucuz GB", sources: "Kaynaklar", liveOf: "canlı" },
    ko: { title: "Knight Online GB", sub: "Sunucu bazlı alış (siteye satarken eline geçen) ve satış (siteden alırken ödediğin) fiyatları.", buy: "Alış", sell: "Satış", bestBuy: "En iyi alış", spread: "Makas", server: "Sunucu", change24: "24 sa", change7: "7 gün", change30: "30 gün", trend: "Trend", signal: "Sinyal", history: "Fiyat geçmişi", side: "Taraf", range: "Aralık", days: "gün", calc: "GB'ni nakde çevirsen", amount: "GB miktarı", fee: "Havale kesintisi (TL)", arb: "Pazarlar arası arbitraj", arbSub: "En ucuz siteden al, en pahalı siteye sat: oran 1'in altındaysa zarar.", noArb: "Bugün hiçbir sunucuda pazarlar arası arbitraj yok. Kâr yalnızca fiyat hareketinden gelir; sinyal sütununa bak.", arbYes: "Oranı 1'in üstünde sunucu var; teslimat ve çekim ücretlerini düş.", cheapestBuy: "En ucuz al", priciestSell: "En pahalı sat", ratio: "Oran", per10: "10 GB'de", viaAgg: "toplayıcı", stale: "bayat", live: "canlı", error: "hata", dataDays: "gün veri", collecting: "Veri birikiyor: her saat bir nokta eklenir; 24 saat ve 7 gün değişimleri dolunca sinyaller güçlenir.", posIn30: "30g aralığında konum", vol: "Oynaklık (7g)", min30: "30g dip", max30: "30g tepe", best: "en iyi", noHist: "Henüz geçmiş yok." },
    sig: { up: "Yükseliyor", down: "Düşüyor", flat: "Yatay", buy: "AL", sell: "SAT", hold: "TUT", low: "düşük güven", med: "orta güven", high: "yüksek güven", what: "Bugün ne yapmalı?", disclaimer: "Sinyaller geçmiş fiyatın 30 günlük aralığındaki konumundan ve 24 saat / 7 gün yönünden türetilir. Yatırım tavsiyesi değildir." },
    cs2: { title: "CS2 nakit çıkış", sub: "Bir ürün seç: CSFloat, Skinport, Steam ve Türk pazar yerlerindeki fiyatı, sonra her satış rotasında eline geçecek net tutarı gör.", search: "Ürün adı yaz: AK-47 | Redline (Field-Tested), Dreams & Nightmares Case…", loaded: "ürün yüklendi", pick: "Bir ürün seç.", csfloat: "CSFloat en düşük", skinport: "Skinport en düşük / medyan", steam: "Steam en düşük ilan", ratio: "Nakit / Steam", listings: "ilan", noPay: "TR'ye ödeme yok", walletOnly: "yalnızca cüzdan", notTop: "popüler listede değil", routes: "Satış rotaları", routesSub: "Fiyatı ve adedi değiştir; en iyi nakit rota yeşil.", qty: "Adet", price: "Satış fiyatın (USD, adet başı)", tlPrice: "itemsatis ilan fiyatın (TL, adet başı)", cfw: "CSFloat çekim %", fxl: "Kur/banka kaybı %", route: "Rota", fees: "Kesintiler", net: "Eline geçen", note: "Not", bestNet: "En iyi nakit net", notCash: "NAKİT DEĞİL: yalnızca Steam cüzdanı", trItem: "Türk pazar yerleri (TL)", liquid: "En likit ürünler", change7: "7g", hist: "Fiyat geçmişi (günlük)" },
    scan: { title: "CS2 fırsat tarayıcı", sub: "Üç rota, oranı en yüksek ürünler. Oran = satış tarafında eline geçen net ÷ alış tarafında ödediğin.", route: "Rota", minPrice: "Min. fiyat (USD)", minQty: "Min. ilan (iki pazar)", rows: "Satır", passed: "ürün filtreyi geçti", above1: "tanesi 1,00 üstü", guide: "Okuma kılavuzu: oran, satış pazarındaki en düşük ilanın hemen altına listeleyip sattığını varsayar; ilan ≠ satış. 1,50 üstü çoğunlukla veri uyuşmazlığıdır (farklı sürüm, tek ucuz ilan). Ürün 7 gün Trade Protection'da kilitli kalır.", buyAt: "Al", sellAt: "Sat", net: "Net", ratio: "Oran", qty: "İlan A / B", r_sk2cf: "Skinport'ta al → CSFloat'ta sat (nakit→nakit)", r_cf2st: "CSFloat'ta al → Steam'de sat (nakit→Steam cüzdanı)", r_st2cf: "Steam'de al → CSFloat'ta sat (koruma ayağı)" },
    alerts: { title: "Uyarılar ve izleme listesi", sub: "“Zero alışı 550 TL'yi geçince Telegram'dan yaz” gibi kurallar. Giriş gerektirir.", soon: "Üyelik sistemi kuruluyor. Hazır olunca burada giriş yapıp kural ekleyebileceksin.", features: ["Sunucu / ürün bazlı fiyat eşiği", "Trend dönüşü (30g dip/tepe) bildirimi", "Telegram ve e-posta", "İzleme listesi ve günlük özet"] },
    pricing: { title: "Planlar", sub: "Fiyat tablosu herkese açık ve ücretsiz kalır. Pro, zaman kazandıran katmandır.", free: "Ücretsiz", pro: "Pro", mo: "/ay", freeF: ["Tüm sunucular ve pazar yerleri", "7 günlük geçmiş", "CS2 hesaplayıcı ve tarayıcı", "Saatlik güncelleme"], proF: ["90+ gün geçmiş ve karşılaştırma", "Sınırsız uyarı (Telegram / e-posta)", "İzleme listesi ve günlük özet", "CSV dışa aktarım ve API anahtarı", "Öncelikli destek"], cta: "Yakında", note: "Ödeme altyapısı (iyzico) bağlanınca açılır; Türkiye'den TL, yurt dışından USD tahsil edilir." },
    about: { title: "Yöntem ve kaynaklar" },
    common: { currency: "Para birimi", lang: "Dil", theme: "Tema", light: "Açık", dark: "Koyu", updated: "güncelleme", loading: "Yükleniyor…", noData: "Veri yok", all: "Tümü", more: "Daha fazla", less: "Daha az", disclaimer: "Bilgi amaçlıdır, yatırım tavsiyesi değildir. NTTGame sözleşmesi GB'nin paraya çevrilmesini, Valve sözleşmesi üçüncü taraf satışını yasaklar; risk sana aittir." },
  },
  en: {
    nav: { home: "Overview", ko: "Knight Online", cs2: "CS2", scan: "Scanner", alerts: "Alerts", pricing: "Plans", about: "Method" },
    hero: { title: "The price radar for game markets", sub: "We collect Knight Online GB and CS2 skin prices from 7 marketplaces every hour, show the trend and what you actually get in cash.", cta: "See opportunities", updated: "Updated", sources: "sources live" },
    kpi: { fx: "FX rate", bestServer: "Most valuable GB", cheapest: "Cheapest GB", sources: "Sources", liveOf: "live" },
    ko: { title: "Knight Online GB", sub: "Per-server buyback (what you get selling to a site) and retail (what you pay buying from a site).", buy: "Buyback", sell: "Retail", bestBuy: "Best buyback", spread: "Spread", server: "Server", change24: "24h", change7: "7d", change30: "30d", trend: "Trend", signal: "Signal", history: "Price history", side: "Side", range: "Range", days: "days", calc: "Cash out your GB", amount: "GB amount", fee: "Bank transfer fee (TL)", arb: "Cross-marketplace arbitrage", arbSub: "Buy at the cheapest site, sell to the highest bidder: ratio below 1 is a loss.", noArb: "No cross-marketplace arbitrage on any server today. Profit only comes from price moves; see the signal column.", arbYes: "A server is above 1.00; subtract delivery and withdrawal fees.", cheapestBuy: "Cheapest buy", priciestSell: "Highest sell", ratio: "Ratio", per10: "per 10 GB", viaAgg: "aggregator", stale: "stale", live: "live", error: "error", dataDays: "days of data", collecting: "Data is accumulating: one point per hour; signals strengthen once 24h and 7d changes fill in.", posIn30: "Position in 30d range", vol: "Volatility (7d)", min30: "30d low", max30: "30d high", best: "best", noHist: "No history yet." },
    sig: { up: "Rising", down: "Falling", flat: "Flat", buy: "BUY", sell: "SELL", hold: "HOLD", low: "low confidence", med: "medium confidence", high: "high confidence", what: "What to do today?", disclaimer: "Signals derive from the price position within its 30-day range and the 24h / 7d direction. Not investment advice." },
    cs2: { title: "CS2 cash-out", sub: "Pick an item: its price on CSFloat, Skinport, Steam and Turkish marketplaces, then the net you receive on each selling route.", search: "Type an item: AK-47 | Redline (Field-Tested), Dreams & Nightmares Case…", loaded: "items loaded", pick: "Pick an item.", csfloat: "CSFloat lowest", skinport: "Skinport lowest / median", steam: "Steam lowest listing", ratio: "Cash / Steam", listings: "listings", noPay: "no payout to TR", walletOnly: "wallet only", notTop: "not in popular list", routes: "Selling routes", routesSub: "Change price and quantity; best cash route in green.", qty: "Qty", price: "Your sale price (USD, each)", tlPrice: "Your itemsatis listing (TL, each)", cfw: "CSFloat withdrawal %", fxl: "FX/bank loss %", route: "Route", fees: "Fees", net: "You receive", note: "Note", bestNet: "Best cash net", notCash: "NOT CASH: Steam wallet only", trItem: "Turkish marketplaces (TL)", liquid: "Most liquid items", change7: "7d", hist: "Price history (daily)" },
    scan: { title: "CS2 opportunity scanner", sub: "Three routes, highest ratios. Ratio = net received on the sell side ÷ paid on the buy side.", route: "Route", minPrice: "Min. price (USD)", minQty: "Min. listings (both)", rows: "Rows", passed: "items passed the filter", above1: "above 1.00", guide: "Reading guide: the ratio assumes you list just under the lowest listing and it sells; listing ≠ sale. Above 1.50 is usually a data mismatch (different version, one cheap listing). Items stay locked 7 days under Trade Protection.", buyAt: "Buy", sellAt: "Sell", net: "Net", ratio: "Ratio", qty: "Listings A / B", r_sk2cf: "Buy on Skinport → sell on CSFloat (cash→cash)", r_cf2st: "Buy on CSFloat → sell on Steam (cash→Steam wallet)", r_st2cf: "Buy on Steam → sell on CSFloat (return leg)" },
    alerts: { title: "Alerts & watchlist", sub: "Rules like “message me on Telegram when Zero buyback crosses 550 TL”. Requires sign-in.", soon: "Accounts are being set up. Once ready you will sign in and add rules here.", features: ["Per-server / per-item price thresholds", "Trend reversal (30d low/high) notifications", "Telegram and e-mail", "Watchlist and daily digest"] },
    pricing: { title: "Plans", sub: "The price tables stay public and free. Pro is the time-saving layer.", free: "Free", pro: "Pro", mo: "/mo", freeF: ["All servers and marketplaces", "7-day history", "CS2 calculator and scanner", "Hourly updates"], proF: ["90+ days of history and comparisons", "Unlimited alerts (Telegram / e-mail)", "Watchlist and daily digest", "CSV export and API key", "Priority support"], cta: "Coming soon", note: "Opens once payments (iyzico) are connected; TL from Türkiye, USD abroad." },
    about: { title: "Method and sources" },
    common: { currency: "Currency", lang: "Language", theme: "Theme", light: "Light", dark: "Dark", updated: "updated", loading: "Loading…", noData: "No data", all: "All", more: "More", less: "Less", disclaimer: "For information only, not investment advice. NTTGame's terms forbid converting GB to money and Valve's terms forbid third-party sales; the risk is yours." },
  },
};
export const useT = (lang) => dict[lang] || dict.tr;
